# ╔════════════════════════════════════════════════════════════════════════════╗
# ║ This file is read only once per server start. Restart server when changed! ║
# ╚════════════════════════════════════════════════════════════════════════════╝

# Site settings
# ─────────────
baseurl: # the subpath of your site, e.g. /blog
# host   : 127.0.0.1
# port   : 4000

# Custom Site variables
# ─────────────────────
show-style-guide: false # Show style guide in footer.
title: Personal startpage

# Build settings
# ──────────────
defaults:
  -
    scope:
      path: "style-guide"
    values:
      layout: style-guide
highlighter: true

exclude:
  - Gemfile
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-menus

sass:
  style: nested
#  style: expanded
#  style: compact
#  style: compressed

collections:
  quicklinks:
  themes: