---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: document
  path: https://personal-startpage.lennertderyck.be/admin/#/page-create?section=themes&pageType=theme
  label: Test
- type: heading
  label: PERSONALIZATION
- type: directory
  path: _quicklinks
  label: Quicklinks
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - quicklink
- type: directory
  path: _themes
  label: Themes
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - theme
upload_dir: themes
public_path: "/themes"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
